"""initial, creating all model

Revision ID: 7988495003a5
Revises: 
Create Date: 2025-05-18 07:05:19.607132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7988495003a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurable_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('help_text', sa.String(length=255), nullable=True),
    sa.Column('widget', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('settings', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurable_options_id'), 'configurable_options', ['id'], unique=False)
    op.create_index(op.f('ix_configurable_options_name'), 'configurable_options', ['name'], unique=False)
    op.create_index(op.f('ix_configurable_options_status'), 'configurable_options', ['status'], unique=False)
    op.create_index(op.f('ix_configurable_options_widget'), 'configurable_options', ['widget'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('product_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_groups_id'), 'product_groups', ['id'], unique=False)
    op.create_index(op.f('ix_product_groups_name'), 'product_groups', ['name'], unique=True)
    op.create_table('configurable_option_choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('choice', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['configurable_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'choice', name='uq_option_choice')
    )
    op.create_index(op.f('ix_configurable_option_choices_id'), 'configurable_option_choices', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Enum('generic', 'openstack', 'hosting', 'domain', 'cdn', name='producttype'), nullable=False),
    sa.Column('price_model', sa.Enum('free', 'fixed_and_dynamic', 'dynamic_or_fixed', name='pricingmodel'), nullable=False),
    sa.Column('auto_setup', sa.Enum('disabled', 'on_order', 'on_first_payment', 'manual', name='productautosetup'), nullable=False),
    sa.Column('provisioning_backend', sa.Enum('openstack', 'cdn', 'database', 'manual', 'external', name='provisioningbackend'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('has_quantity', sa.Boolean(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('taxable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['product_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('configurable_option_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value_id', sa.UUID(), nullable=True),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('cycle', sa.Enum('onetime', 'hour', 'month', 'year', name='cycleperiods'), nullable=False),
    sa.Column('cycle_multiplier', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('setup_fee_entire_quantity', sa.Boolean(), nullable=True),
    sa.Column('is_relative_price', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['configurable_options.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['configurable_option_choices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurable_option_cycles_cycle'), 'configurable_option_cycles', ['cycle'], unique=False)
    op.create_index(op.f('ix_configurable_option_cycles_cycle_multiplier'), 'configurable_option_cycles', ['cycle_multiplier'], unique=False)
    op.create_index(op.f('ix_configurable_option_cycles_id'), 'configurable_option_cycles', ['id'], unique=False)
    op.create_table('product_configurable_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('configurable_option_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['configurable_option_id'], ['configurable_options.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'configurable_option_id', name='uq_product_configurable')
    )
    op.create_index(op.f('ix_product_configurable_options_id'), 'product_configurable_options', ['id'], unique=False)
    op.create_table('product_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cycle', sa.Enum('onetime', 'hour', 'month', 'year', name='cycleperiods'), nullable=False),
    sa.Column('cycle_multiplier', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fixed_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('setup_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('setup_fee_entire_quantity', sa.Boolean(), nullable=True),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('is_relative_price', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('public', 'private', 'retired', name='publicstatuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'cycle', 'cycle_multiplier', 'currency_id', name='uq_product_cycle')
    )
    op.create_index(op.f('ix_product_cycles_id'), 'product_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_product_cycles_status'), 'product_cycles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_cycles_status'), table_name='product_cycles')
    op.drop_index(op.f('ix_product_cycles_id'), table_name='product_cycles')
    op.drop_table('product_cycles')
    op.drop_index(op.f('ix_product_configurable_options_id'), table_name='product_configurable_options')
    op.drop_table('product_configurable_options')
    op.drop_index(op.f('ix_configurable_option_cycles_id'), table_name='configurable_option_cycles')
    op.drop_index(op.f('ix_configurable_option_cycles_cycle_multiplier'), table_name='configurable_option_cycles')
    op.drop_index(op.f('ix_configurable_option_cycles_cycle'), table_name='configurable_option_cycles')
    op.drop_table('configurable_option_cycles')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_configurable_option_choices_id'), table_name='configurable_option_choices')
    op.drop_table('configurable_option_choices')
    op.drop_index(op.f('ix_product_groups_name'), table_name='product_groups')
    op.drop_index(op.f('ix_product_groups_id'), table_name='product_groups')
    op.drop_table('product_groups')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_configurable_options_widget'), table_name='configurable_options')
    op.drop_index(op.f('ix_configurable_options_status'), table_name='configurable_options')
    op.drop_index(op.f('ix_configurable_options_name'), table_name='configurable_options')
    op.drop_index(op.f('ix_configurable_options_id'), table_name='configurable_options')
    op.drop_table('configurable_options')
    # ### end Alembic commands ###
