"""Fix settings column to use JSONB

Revision ID: 7cdb144c2820
Revises: 7988495003a5
Create Date: 2025-05-18 12:06:27.545213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cdb144c2820'
down_revision: Union[str, None] = '7988495003a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configurable_options', 'settings',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
                postgresql_using='settings::jsonb',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configurable_options', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),postgresql_using='settings::text',
               existing_nullable=True)
    # ### end Alembic commands ###
